[2024-05-23 12:23:47,966] - 97  werkzeug - INFO- [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-05-23 12:23:47,974] - 97  werkzeug - INFO- [33mPress CTRL+C to quit[0m
[2024-05-23 12:23:52,051] - 838  app - ERROR- Exception on /recommend [POST]
Traceback (most recent call last):
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\app.py", line 44, in predict_datapoint
    return render_template("result.html",recommendations=recommendations,product=selected_products)
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\templates\result.html", line 50, in top-level template code
    {% if len(recommendations)==0 %}
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\jinja2\utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'len' is undefined
[2024-05-23 12:23:52,056] - 97  werkzeug - INFO- 127.0.0.1 - - [23/May/2024 12:23:52] "[35m[1mPOST /recommend HTTP/1.1[0m" 500 -
[2024-05-23 12:23:55,598] - 97  werkzeug - INFO- 127.0.0.1 - - [23/May/2024 12:23:55] "GET /recommend HTTP/1.1" 200 -
[2024-05-23 12:23:59,084] - 838  app - ERROR- Exception on /recommend [POST]
Traceback (most recent call last):
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\app.py", line 44, in predict_datapoint
    return render_template("result.html",recommendations=recommendations,product=selected_products)
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\templates\result.html", line 50, in top-level template code
    {% if len(recommendations)==0 %}
  File "D:\Studies\Data Science\Project Pro\Market Basket Analysis\env\lib\site-packages\jinja2\utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'len' is undefined
[2024-05-23 12:23:59,085] - 97  werkzeug - INFO- 127.0.0.1 - - [23/May/2024 12:23:59] "[35m[1mPOST /recommend HTTP/1.1[0m" 500 -
